<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TimeInOut', 'doctrine');

/**
 * BaseTimeInOut
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $day_type_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property date $task_date
 * @property time $time_in
 * @property time $time_out
 * @property time $total_hrs
 * @property enum $status
 * @property DayType $DayType
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getUserId()      Returns the current record's "user_id" value
 * @method integer   getDayTypeId()   Returns the current record's "day_type_id" value
 * @method timestamp getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()   Returns the current record's "updated_at" value
 * @method date      getTaskDate()    Returns the current record's "task_date" value
 * @method time      getTimeIn()      Returns the current record's "time_in" value
 * @method time      getTimeOut()     Returns the current record's "time_out" value
 * @method time      getTotalHrs()    Returns the current record's "total_hrs" value
 * @method enum      getStatus()      Returns the current record's "status" value
 * @method DayType   getDayType()     Returns the current record's "DayType" value
 * @method TimeInOut setId()          Sets the current record's "id" value
 * @method TimeInOut setUserId()      Sets the current record's "user_id" value
 * @method TimeInOut setDayTypeId()   Sets the current record's "day_type_id" value
 * @method TimeInOut setCreatedAt()   Sets the current record's "created_at" value
 * @method TimeInOut setUpdatedAt()   Sets the current record's "updated_at" value
 * @method TimeInOut setTaskDate()    Sets the current record's "task_date" value
 * @method TimeInOut setTimeIn()      Sets the current record's "time_in" value
 * @method TimeInOut setTimeOut()     Sets the current record's "time_out" value
 * @method TimeInOut setTotalHrs()    Sets the current record's "total_hrs" value
 * @method TimeInOut setStatus()      Sets the current record's "status" value
 * @method TimeInOut setDayType()     Sets the current record's "DayType" value
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTimeInOut extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('time_in_out');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('day_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('task_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('time_in', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('time_out', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('total_hrs', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'enum', 3, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'IN',
              1 => 'OUT',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DayType', array(
             'local' => 'day_type_id',
             'foreign' => 'id'));
    }
}