<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Grantee', 'doctrine');

/**
 * BaseGrantee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $grantee_details_id
 * @property integer $country_id
 * @property integer $cem_cemetery_id
 * @property integer $ar_area_id
 * @property integer $ar_section_id
 * @property integer $ar_row_id
 * @property integer $ar_plot_id
 * @property integer $ar_grave_id
 * @property integer $ar_grave_status_id
 * @property integer $fnd_fndirector_id
 * @property integer $grantee_identity_id
 * @property integer $catalog_id
 * @property integer $payment_id
 * @property string $grantee_identity_number
 * @property string $receipt_number
 * @property string $control_number
 * @property string $invoice_number
 * @property date $date_of_purchase
 * @property integer $cost
 * @property date $tenure_expiry_date
 * @property integer $user_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property GranteeDetails $GranteeDetails
 * @property Country $Country
 * @property CemCemetery $CemCemetery
 * @property ArArea $ArArea
 * @property ArSection $ArSection
 * @property ArRow $ArRow
 * @property ArPlot $ArPlot
 * @property ArGrave $ArGrave
 * @property GranteeIdentity $GranteeIdentity
 * @property Catalog $Catalog
 * 
 * @method integer         getId()                      Returns the current record's "id" value
 * @method integer         getGranteeDetailsId()        Returns the current record's "grantee_details_id" value
 * @method integer         getCountryId()               Returns the current record's "country_id" value
 * @method integer         getCemCemeteryId()           Returns the current record's "cem_cemetery_id" value
 * @method integer         getArAreaId()                Returns the current record's "ar_area_id" value
 * @method integer         getArSectionId()             Returns the current record's "ar_section_id" value
 * @method integer         getArRowId()                 Returns the current record's "ar_row_id" value
 * @method integer         getArPlotId()                Returns the current record's "ar_plot_id" value
 * @method integer         getArGraveId()               Returns the current record's "ar_grave_id" value
 * @method integer         getArGraveStatusId()         Returns the current record's "ar_grave_status_id" value
 * @method integer         getFndFndirectorId()         Returns the current record's "fnd_fndirector_id" value
 * @method integer         getGranteeIdentityId()       Returns the current record's "grantee_identity_id" value
 * @method integer         getCatalogId()               Returns the current record's "catalog_id" value
 * @method integer         getPaymentId()               Returns the current record's "payment_id" value
 * @method string          getGranteeIdentityNumber()   Returns the current record's "grantee_identity_number" value
 * @method string          getReceiptNumber()           Returns the current record's "receipt_number" value
 * @method string          getControlNumber()           Returns the current record's "control_number" value
 * @method string          getInvoiceNumber()           Returns the current record's "invoice_number" value
 * @method date            getDateOfPurchase()          Returns the current record's "date_of_purchase" value
 * @method integer         getCost()                    Returns the current record's "cost" value
 * @method date            getTenureExpiryDate()        Returns the current record's "tenure_expiry_date" value
 * @method integer         getUserId()                  Returns the current record's "user_id" value
 * @method timestamp       getCreatedAt()               Returns the current record's "created_at" value
 * @method timestamp       getUpdatedAt()               Returns the current record's "updated_at" value
 * @method GranteeDetails  getGranteeDetails()          Returns the current record's "GranteeDetails" value
 * @method Country         getCountry()                 Returns the current record's "Country" value
 * @method CemCemetery     getCemCemetery()             Returns the current record's "CemCemetery" value
 * @method ArArea          getArArea()                  Returns the current record's "ArArea" value
 * @method ArSection       getArSection()               Returns the current record's "ArSection" value
 * @method ArRow           getArRow()                   Returns the current record's "ArRow" value
 * @method ArPlot          getArPlot()                  Returns the current record's "ArPlot" value
 * @method ArGrave         getArGrave()                 Returns the current record's "ArGrave" value
 * @method GranteeIdentity getGranteeIdentity()         Returns the current record's "GranteeIdentity" value
 * @method Catalog         getCatalog()                 Returns the current record's "Catalog" value
 * @method Grantee         setId()                      Sets the current record's "id" value
 * @method Grantee         setGranteeDetailsId()        Sets the current record's "grantee_details_id" value
 * @method Grantee         setCountryId()               Sets the current record's "country_id" value
 * @method Grantee         setCemCemeteryId()           Sets the current record's "cem_cemetery_id" value
 * @method Grantee         setArAreaId()                Sets the current record's "ar_area_id" value
 * @method Grantee         setArSectionId()             Sets the current record's "ar_section_id" value
 * @method Grantee         setArRowId()                 Sets the current record's "ar_row_id" value
 * @method Grantee         setArPlotId()                Sets the current record's "ar_plot_id" value
 * @method Grantee         setArGraveId()               Sets the current record's "ar_grave_id" value
 * @method Grantee         setArGraveStatusId()         Sets the current record's "ar_grave_status_id" value
 * @method Grantee         setFndFndirectorId()         Sets the current record's "fnd_fndirector_id" value
 * @method Grantee         setGranteeIdentityId()       Sets the current record's "grantee_identity_id" value
 * @method Grantee         setCatalogId()               Sets the current record's "catalog_id" value
 * @method Grantee         setPaymentId()               Sets the current record's "payment_id" value
 * @method Grantee         setGranteeIdentityNumber()   Sets the current record's "grantee_identity_number" value
 * @method Grantee         setReceiptNumber()           Sets the current record's "receipt_number" value
 * @method Grantee         setControlNumber()           Sets the current record's "control_number" value
 * @method Grantee         setInvoiceNumber()           Sets the current record's "invoice_number" value
 * @method Grantee         setDateOfPurchase()          Sets the current record's "date_of_purchase" value
 * @method Grantee         setCost()                    Sets the current record's "cost" value
 * @method Grantee         setTenureExpiryDate()        Sets the current record's "tenure_expiry_date" value
 * @method Grantee         setUserId()                  Sets the current record's "user_id" value
 * @method Grantee         setCreatedAt()               Sets the current record's "created_at" value
 * @method Grantee         setUpdatedAt()               Sets the current record's "updated_at" value
 * @method Grantee         setGranteeDetails()          Sets the current record's "GranteeDetails" value
 * @method Grantee         setCountry()                 Sets the current record's "Country" value
 * @method Grantee         setCemCemetery()             Sets the current record's "CemCemetery" value
 * @method Grantee         setArArea()                  Sets the current record's "ArArea" value
 * @method Grantee         setArSection()               Sets the current record's "ArSection" value
 * @method Grantee         setArRow()                   Sets the current record's "ArRow" value
 * @method Grantee         setArPlot()                  Sets the current record's "ArPlot" value
 * @method Grantee         setArGrave()                 Sets the current record's "ArGrave" value
 * @method Grantee         setGranteeIdentity()         Sets the current record's "GranteeIdentity" value
 * @method Grantee         setCatalog()                 Sets the current record's "Catalog" value
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrantee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grantee');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('grantee_details_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('country_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cem_cemetery_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_area_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_section_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_row_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_plot_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_grave_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_grave_status_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fnd_fndirector_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('grantee_identity_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('catalog_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('payment_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('grantee_identity_number', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('receipt_number', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('control_number', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('invoice_number', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('date_of_purchase', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cost', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tenure_expiry_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GranteeDetails', array(
             'local' => 'grantee_details_id',
             'foreign' => 'id'));

        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id'));

        $this->hasOne('CemCemetery', array(
             'local' => 'cem_cemetery_id',
             'foreign' => 'id'));

        $this->hasOne('ArArea', array(
             'local' => 'ar_area_id',
             'foreign' => 'id'));

        $this->hasOne('ArSection', array(
             'local' => 'ar_section_id',
             'foreign' => 'id'));

        $this->hasOne('ArRow', array(
             'local' => 'ar_row_id',
             'foreign' => 'id'));

        $this->hasOne('ArPlot', array(
             'local' => 'ar_plot_id',
             'foreign' => 'id'));

        $this->hasOne('ArGrave', array(
             'local' => 'ar_grave_id',
             'foreign' => 'id'));

        $this->hasOne('GranteeIdentity', array(
             'local' => 'grantee_identity_id',
             'foreign' => 'id'));

        $this->hasOne('Catalog', array(
             'local' => 'catalog_id',
             'foreign' => 'id'));
    }
}