<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CalTemplate', 'doctrine');

/**
 * BaseCalTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cal_template_id
 * @property integer $equ_equipment_id
 * @property string $name
 * @property string $description
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property string $param_set
 * @property Doctrine_Collection $CalSchedular
 * 
 * @method integer             getCalTemplateId()    Returns the current record's "cal_template_id" value
 * @method integer             getEquEquipmentId()   Returns the current record's "equ_equipment_id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method timestamp           getCreatedAt()        Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()        Returns the current record's "updated_at" value
 * @method string              getParamSet()         Returns the current record's "param_set" value
 * @method Doctrine_Collection getCalSchedular()     Returns the current record's "CalSchedular" collection
 * @method CalTemplate         setCalTemplateId()    Sets the current record's "cal_template_id" value
 * @method CalTemplate         setEquEquipmentId()   Sets the current record's "equ_equipment_id" value
 * @method CalTemplate         setName()             Sets the current record's "name" value
 * @method CalTemplate         setDescription()      Sets the current record's "description" value
 * @method CalTemplate         setCreatedAt()        Sets the current record's "created_at" value
 * @method CalTemplate         setUpdatedAt()        Sets the current record's "updated_at" value
 * @method CalTemplate         setParamSet()         Sets the current record's "param_set" value
 * @method CalTemplate         setCalSchedular()     Sets the current record's "CalSchedular" collection
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCalTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cal_template');
        $this->hasColumn('cal_template_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('equ_equipment_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('param_set', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CalSchedular', array(
             'local' => 'cal_template_id',
             'foreign' => 'cal_template_id'));
    }
}