<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ArGraveStatus', 'doctrine');

/**
 * BaseArGraveStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $grave_status
 * @property integer $is_enabled
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $ArGrave
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getGraveStatus()  Returns the current record's "grave_status" value
 * @method integer             getIsEnabled()    Returns the current record's "is_enabled" value
 * @method timestamp           getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()    Returns the current record's "updated_at" value
 * @method Doctrine_Collection getArGrave()      Returns the current record's "ArGrave" collection
 * @method ArGraveStatus       setId()           Sets the current record's "id" value
 * @method ArGraveStatus       setGraveStatus()  Sets the current record's "grave_status" value
 * @method ArGraveStatus       setIsEnabled()    Sets the current record's "is_enabled" value
 * @method ArGraveStatus       setCreatedAt()    Sets the current record's "created_at" value
 * @method ArGraveStatus       setUpdatedAt()    Sets the current record's "updated_at" value
 * @method ArGraveStatus       setArGrave()      Sets the current record's "ArGrave" collection
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArGraveStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ar_grave_status');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('grave_status', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('is_enabled', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ArGrave', array(
             'local' => 'id',
             'foreign' => 'ar_grave_status_id'));
    }
}