<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CemMail', 'doctrine');

/**
 * BaseCemMail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $mail_subject
 * @property string $mail_body
 * @property string $attached_file_name
 * @property integer $mail_status
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $CemMailUsers
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getMailSubject()        Returns the current record's "mail_subject" value
 * @method string              getMailBody()           Returns the current record's "mail_body" value
 * @method string              getAttachedFileName()   Returns the current record's "attached_file_name" value
 * @method integer             getMailStatus()         Returns the current record's "mail_status" value
 * @method timestamp           getCreatedAt()          Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()          Returns the current record's "updated_at" value
 * @method Doctrine_Collection getCemMailUsers()       Returns the current record's "CemMailUsers" collection
 * @method CemMail             setId()                 Sets the current record's "id" value
 * @method CemMail             setMailSubject()        Sets the current record's "mail_subject" value
 * @method CemMail             setMailBody()           Sets the current record's "mail_body" value
 * @method CemMail             setAttachedFileName()   Sets the current record's "attached_file_name" value
 * @method CemMail             setMailStatus()         Sets the current record's "mail_status" value
 * @method CemMail             setCreatedAt()          Sets the current record's "created_at" value
 * @method CemMail             setUpdatedAt()          Sets the current record's "updated_at" value
 * @method CemMail             setCemMailUsers()       Sets the current record's "CemMailUsers" collection
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCemMail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cem_mail');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('mail_subject', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('mail_body', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('attached_file_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('mail_status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CemMailUsers', array(
             'local' => 'id',
             'foreign' => 'cem_mail_id'));
    }
}