<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LetterConfirmation', 'doctrine');

/**
 * BaseLetterConfirmation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $interment_booking_five_id
 * @property string $mail_content_type
 * @property integer $confirmed
 * @property string $token
 * @property IntermentBookingFive $IntermentBookingFive
 * 
 * @method integer              getId()                        Returns the current record's "id" value
 * @method integer              getIntermentBookingFiveId()    Returns the current record's "interment_booking_five_id" value
 * @method string               getMailContentType()           Returns the current record's "mail_content_type" value
 * @method integer              getConfirmed()                 Returns the current record's "confirmed" value
 * @method string               getToken()                     Returns the current record's "token" value
 * @method IntermentBookingFive getIntermentBookingFive()      Returns the current record's "IntermentBookingFive" value
 * @method LetterConfirmation   setId()                        Sets the current record's "id" value
 * @method LetterConfirmation   setIntermentBookingFiveId()    Sets the current record's "interment_booking_five_id" value
 * @method LetterConfirmation   setMailContentType()           Sets the current record's "mail_content_type" value
 * @method LetterConfirmation   setConfirmed()                 Sets the current record's "confirmed" value
 * @method LetterConfirmation   setToken()                     Sets the current record's "token" value
 * @method LetterConfirmation   setIntermentBookingFive()      Sets the current record's "IntermentBookingFive" value
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLetterConfirmation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('letter_confirmation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('interment_booking_five_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('mail_content_type', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('confirmed', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('IntermentBookingFive', array(
             'local' => 'interment_booking_five_id',
             'foreign' => 'id'));
    }
}