<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CemCemeteryStonemason', 'doctrine');

/**
 * BaseCemCemeteryStonemason
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cem_cemetery_id
 * @property integer $cms_stonemason_id
 * @property CemCemetery $CemCemetery
 * @property CemStonemason $CemStonemason
 * 
 * @method integer               getId()                Returns the current record's "id" value
 * @method integer               getCemCemeteryId()     Returns the current record's "cem_cemetery_id" value
 * @method integer               getCmsStonemasonId()   Returns the current record's "cms_stonemason_id" value
 * @method CemCemetery           getCemCemetery()       Returns the current record's "CemCemetery" value
 * @method CemStonemason         getCemStonemason()     Returns the current record's "CemStonemason" value
 * @method CemCemeteryStonemason setId()                Sets the current record's "id" value
 * @method CemCemeteryStonemason setCemCemeteryId()     Sets the current record's "cem_cemetery_id" value
 * @method CemCemeteryStonemason setCmsStonemasonId()   Sets the current record's "cms_stonemason_id" value
 * @method CemCemeteryStonemason setCemCemetery()       Sets the current record's "CemCemetery" value
 * @method CemCemeteryStonemason setCemStonemason()     Sets the current record's "CemStonemason" value
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCemCemeteryStonemason extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cem_cemetery_stonemason');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cem_cemetery_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cms_stonemason_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CemCemetery', array(
             'local' => 'cem_cemetery_id',
             'foreign' => 'id'));

        $this->hasOne('CemStonemason', array(
             'local' => 'cms_stonemason_id',
             'foreign' => 'id'));
    }
}