<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AwardPayRate', 'doctrine');

/**
 * BaseAwardPayRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_award
 * @property time $overtime_hrs
 * @property integer $overtime_pay_rate
 * @property Award $Award
 * 
 * @method integer      getId()                Returns the current record's "id" value
 * @method integer      getIdAward()           Returns the current record's "id_award" value
 * @method time         getOvertimeHrs()       Returns the current record's "overtime_hrs" value
 * @method integer      getOvertimePayRate()   Returns the current record's "overtime_pay_rate" value
 * @method Award        getAward()             Returns the current record's "Award" value
 * @method AwardPayRate setId()                Sets the current record's "id" value
 * @method AwardPayRate setIdAward()           Sets the current record's "id_award" value
 * @method AwardPayRate setOvertimeHrs()       Sets the current record's "overtime_hrs" value
 * @method AwardPayRate setOvertimePayRate()   Sets the current record's "overtime_pay_rate" value
 * @method AwardPayRate setAward()             Sets the current record's "Award" value
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAwardPayRate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('award_pay_rate');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_award', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('overtime_hrs', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('overtime_pay_rate', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Award', array(
             'local' => 'id_award',
             'foreign' => 'id'));
    }
}