<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CemWorktypeStonemason', 'doctrine');

/**
 * BaseCemWorktypeStonemason
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $is_enabled
 * 
 * @method integer               getId()         Returns the current record's "id" value
 * @method string                getName()       Returns the current record's "name" value
 * @method integer               getIsEnabled()  Returns the current record's "is_enabled" value
 * @method CemWorktypeStonemason setId()         Sets the current record's "id" value
 * @method CemWorktypeStonemason setName()       Sets the current record's "name" value
 * @method CemWorktypeStonemason setIsEnabled()  Sets the current record's "is_enabled" value
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCemWorktypeStonemason extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cem_worktype_stonemason');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('is_enabled', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}