<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('IntermentBookingFive', 'doctrine');

/**
 * BaseIntermentBookingFive
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $interment_booking_id
 * @property integer $mail_content_id
 * @property enum $status
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property IntermentBooking $IntermentBooking
 * @property MailContent $MailContent
 * @property Doctrine_Collection $LetterConfirmation
 * 
 * @method integer              getId()                   Returns the current record's "id" value
 * @method integer              getIntermentBookingId()   Returns the current record's "interment_booking_id" value
 * @method integer              getMailContentId()        Returns the current record's "mail_content_id" value
 * @method enum                 getStatus()               Returns the current record's "status" value
 * @method timestamp            getCreatedAt()            Returns the current record's "created_at" value
 * @method timestamp            getUpdatedAt()            Returns the current record's "updated_at" value
 * @method IntermentBooking     getIntermentBooking()     Returns the current record's "IntermentBooking" value
 * @method MailContent          getMailContent()          Returns the current record's "MailContent" value
 * @method Doctrine_Collection  getLetterConfirmation()   Returns the current record's "LetterConfirmation" collection
 * @method IntermentBookingFive setId()                   Sets the current record's "id" value
 * @method IntermentBookingFive setIntermentBookingId()   Sets the current record's "interment_booking_id" value
 * @method IntermentBookingFive setMailContentId()        Sets the current record's "mail_content_id" value
 * @method IntermentBookingFive setStatus()               Sets the current record's "status" value
 * @method IntermentBookingFive setCreatedAt()            Sets the current record's "created_at" value
 * @method IntermentBookingFive setUpdatedAt()            Sets the current record's "updated_at" value
 * @method IntermentBookingFive setIntermentBooking()     Sets the current record's "IntermentBooking" value
 * @method IntermentBookingFive setMailContent()          Sets the current record's "MailContent" value
 * @method IntermentBookingFive setLetterConfirmation()   Sets the current record's "LetterConfirmation" collection
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIntermentBookingFive extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('interment_booking_five');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('interment_booking_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('mail_content_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'enum', 3, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'No',
              1 => 'Yes',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('IntermentBooking', array(
             'local' => 'interment_booking_id',
             'foreign' => 'id'));

        $this->hasOne('MailContent', array(
             'local' => 'mail_content_id',
             'foreign' => 'id'));

        $this->hasMany('LetterConfirmation', array(
             'local' => 'id',
             'foreign' => 'interment_booking_five_id'));
    }
}