<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Workflow', 'doctrine');

/**
 * BaseWorkflow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $country_id
 * @property integer $cem_cemetery_id
 * @property integer $ar_area_id
 * @property integer $ar_section_id
 * @property integer $ar_row_id
 * @property integer $ar_plot_id
 * @property integer $ar_grave_id
 * @property date $work_date
 * @property string $title
 * @property string $name
 * @property string $surname
 * @property string $email
 * @property string $area_code
 * @property string $telephone
 * @property integer $department_delegation
 * @property string $work_description
 * @property integer $completed_by
 * @property date $completion_date
 * @property string $action_taken
 * @property string $feed_charges
 * @property string $receipt_number
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Country $Country
 * @property CemCemetery $CemCemetery
 * @property ArArea $ArArea
 * @property ArSection $ArSection
 * @property ArRow $ArRow
 * @property ArPlot $ArPlot
 * @property ArGrave $ArGrave
 * @property DepartmentDelegation $DepartmentDelegation
 * 
 * @method integer              getId()                    Returns the current record's "id" value
 * @method integer              getCountryId()             Returns the current record's "country_id" value
 * @method integer              getCemCemeteryId()         Returns the current record's "cem_cemetery_id" value
 * @method integer              getArAreaId()              Returns the current record's "ar_area_id" value
 * @method integer              getArSectionId()           Returns the current record's "ar_section_id" value
 * @method integer              getArRowId()               Returns the current record's "ar_row_id" value
 * @method integer              getArPlotId()              Returns the current record's "ar_plot_id" value
 * @method integer              getArGraveId()             Returns the current record's "ar_grave_id" value
 * @method date                 getWorkDate()              Returns the current record's "work_date" value
 * @method string               getTitle()                 Returns the current record's "title" value
 * @method string               getName()                  Returns the current record's "name" value
 * @method string               getSurname()               Returns the current record's "surname" value
 * @method string               getEmail()                 Returns the current record's "email" value
 * @method string               getAreaCode()              Returns the current record's "area_code" value
 * @method string               getTelephone()             Returns the current record's "telephone" value
 * @method integer              getDepartmentDelegation()  Returns the current record's "department_delegation" value
 * @method string               getWorkDescription()       Returns the current record's "work_description" value
 * @method integer              getCompletedBy()           Returns the current record's "completed_by" value
 * @method date                 getCompletionDate()        Returns the current record's "completion_date" value
 * @method string               getActionTaken()           Returns the current record's "action_taken" value
 * @method string               getFeedCharges()           Returns the current record's "feed_charges" value
 * @method string               getReceiptNumber()         Returns the current record's "receipt_number" value
 * @method timestamp            getCreatedAt()             Returns the current record's "created_at" value
 * @method timestamp            getUpdatedAt()             Returns the current record's "updated_at" value
 * @method Country              getCountry()               Returns the current record's "Country" value
 * @method CemCemetery          getCemCemetery()           Returns the current record's "CemCemetery" value
 * @method ArArea               getArArea()                Returns the current record's "ArArea" value
 * @method ArSection            getArSection()             Returns the current record's "ArSection" value
 * @method ArRow                getArRow()                 Returns the current record's "ArRow" value
 * @method ArPlot               getArPlot()                Returns the current record's "ArPlot" value
 * @method ArGrave              getArGrave()               Returns the current record's "ArGrave" value
 * @method DepartmentDelegation getDepartmentDelegation()  Returns the current record's "DepartmentDelegation" value
 * @method Workflow             setId()                    Sets the current record's "id" value
 * @method Workflow             setCountryId()             Sets the current record's "country_id" value
 * @method Workflow             setCemCemeteryId()         Sets the current record's "cem_cemetery_id" value
 * @method Workflow             setArAreaId()              Sets the current record's "ar_area_id" value
 * @method Workflow             setArSectionId()           Sets the current record's "ar_section_id" value
 * @method Workflow             setArRowId()               Sets the current record's "ar_row_id" value
 * @method Workflow             setArPlotId()              Sets the current record's "ar_plot_id" value
 * @method Workflow             setArGraveId()             Sets the current record's "ar_grave_id" value
 * @method Workflow             setWorkDate()              Sets the current record's "work_date" value
 * @method Workflow             setTitle()                 Sets the current record's "title" value
 * @method Workflow             setName()                  Sets the current record's "name" value
 * @method Workflow             setSurname()               Sets the current record's "surname" value
 * @method Workflow             setEmail()                 Sets the current record's "email" value
 * @method Workflow             setAreaCode()              Sets the current record's "area_code" value
 * @method Workflow             setTelephone()             Sets the current record's "telephone" value
 * @method Workflow             setDepartmentDelegation()  Sets the current record's "department_delegation" value
 * @method Workflow             setWorkDescription()       Sets the current record's "work_description" value
 * @method Workflow             setCompletedBy()           Sets the current record's "completed_by" value
 * @method Workflow             setCompletionDate()        Sets the current record's "completion_date" value
 * @method Workflow             setActionTaken()           Sets the current record's "action_taken" value
 * @method Workflow             setFeedCharges()           Sets the current record's "feed_charges" value
 * @method Workflow             setReceiptNumber()         Sets the current record's "receipt_number" value
 * @method Workflow             setCreatedAt()             Sets the current record's "created_at" value
 * @method Workflow             setUpdatedAt()             Sets the current record's "updated_at" value
 * @method Workflow             setCountry()               Sets the current record's "Country" value
 * @method Workflow             setCemCemetery()           Sets the current record's "CemCemetery" value
 * @method Workflow             setArArea()                Sets the current record's "ArArea" value
 * @method Workflow             setArSection()             Sets the current record's "ArSection" value
 * @method Workflow             setArRow()                 Sets the current record's "ArRow" value
 * @method Workflow             setArPlot()                Sets the current record's "ArPlot" value
 * @method Workflow             setArGrave()               Sets the current record's "ArGrave" value
 * @method Workflow             setDepartmentDelegation()  Sets the current record's "DepartmentDelegation" value
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkflow extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('workflow');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('country_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cem_cemetery_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_area_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_section_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_row_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_plot_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_grave_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('work_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('surname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('area_code', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('telephone', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('department_delegation', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('work_description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('completed_by', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('completion_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('action_taken', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('feed_charges', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('receipt_number', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id'));

        $this->hasOne('CemCemetery', array(
             'local' => 'cem_cemetery_id',
             'foreign' => 'id'));

        $this->hasOne('ArArea', array(
             'local' => 'ar_area_id',
             'foreign' => 'id'));

        $this->hasOne('ArSection', array(
             'local' => 'ar_section_id',
             'foreign' => 'id'));

        $this->hasOne('ArRow', array(
             'local' => 'ar_row_id',
             'foreign' => 'id'));

        $this->hasOne('ArPlot', array(
             'local' => 'ar_plot_id',
             'foreign' => 'id'));

        $this->hasOne('ArGrave', array(
             'local' => 'ar_grave_id',
             'foreign' => 'id'));

        $this->hasOne('DepartmentDelegation', array(
             'local' => 'department_delegation',
             'foreign' => 'id'));
    }
}