<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ArPlot', 'doctrine');

/**
 * BaseArPlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $country_id
 * @property integer $cem_cemetery_id
 * @property integer $ar_area_id
 * @property integer $ar_section_id
 * @property integer $ar_row_id
 * @property string $plot_name
 * @property integer $is_enabled
 * @property string $plot_user
 * @property string $length
 * @property string $width
 * @property string $depth
 * @property string $plot_map_path
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Country $Country
 * @property CemCemetery $CemCemetery
 * @property ArArea $ArArea
 * @property ArSection $ArSection
 * @property ArRow $ArRow
 * @property Doctrine_Collection $ArGrave
 * @property Doctrine_Collection $ArGraveMaintenance
 * @property Doctrine_Collection $Grantee
 * @property Doctrine_Collection $GraveLink
 * @property Doctrine_Collection $IntermentBooking
 * @property Doctrine_Collection $Workflow
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getCountryId()          Returns the current record's "country_id" value
 * @method integer             getCemCemeteryId()      Returns the current record's "cem_cemetery_id" value
 * @method integer             getArAreaId()           Returns the current record's "ar_area_id" value
 * @method integer             getArSectionId()        Returns the current record's "ar_section_id" value
 * @method integer             getArRowId()            Returns the current record's "ar_row_id" value
 * @method string              getPlotName()           Returns the current record's "plot_name" value
 * @method integer             getIsEnabled()          Returns the current record's "is_enabled" value
 * @method string              getPlotUser()           Returns the current record's "plot_user" value
 * @method string              getLength()             Returns the current record's "length" value
 * @method string              getWidth()              Returns the current record's "width" value
 * @method string              getDepth()              Returns the current record's "depth" value
 * @method string              getPlotMapPath()        Returns the current record's "plot_map_path" value
 * @method timestamp           getCreatedAt()          Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()          Returns the current record's "updated_at" value
 * @method Country             getCountry()            Returns the current record's "Country" value
 * @method CemCemetery         getCemCemetery()        Returns the current record's "CemCemetery" value
 * @method ArArea              getArArea()             Returns the current record's "ArArea" value
 * @method ArSection           getArSection()          Returns the current record's "ArSection" value
 * @method ArRow               getArRow()              Returns the current record's "ArRow" value
 * @method Doctrine_Collection getArGrave()            Returns the current record's "ArGrave" collection
 * @method Doctrine_Collection getArGraveMaintenance() Returns the current record's "ArGraveMaintenance" collection
 * @method Doctrine_Collection getGrantee()            Returns the current record's "Grantee" collection
 * @method Doctrine_Collection getGraveLink()          Returns the current record's "GraveLink" collection
 * @method Doctrine_Collection getIntermentBooking()   Returns the current record's "IntermentBooking" collection
 * @method Doctrine_Collection getWorkflow()           Returns the current record's "Workflow" collection
 * @method ArPlot              setId()                 Sets the current record's "id" value
 * @method ArPlot              setCountryId()          Sets the current record's "country_id" value
 * @method ArPlot              setCemCemeteryId()      Sets the current record's "cem_cemetery_id" value
 * @method ArPlot              setArAreaId()           Sets the current record's "ar_area_id" value
 * @method ArPlot              setArSectionId()        Sets the current record's "ar_section_id" value
 * @method ArPlot              setArRowId()            Sets the current record's "ar_row_id" value
 * @method ArPlot              setPlotName()           Sets the current record's "plot_name" value
 * @method ArPlot              setIsEnabled()          Sets the current record's "is_enabled" value
 * @method ArPlot              setPlotUser()           Sets the current record's "plot_user" value
 * @method ArPlot              setLength()             Sets the current record's "length" value
 * @method ArPlot              setWidth()              Sets the current record's "width" value
 * @method ArPlot              setDepth()              Sets the current record's "depth" value
 * @method ArPlot              setPlotMapPath()        Sets the current record's "plot_map_path" value
 * @method ArPlot              setCreatedAt()          Sets the current record's "created_at" value
 * @method ArPlot              setUpdatedAt()          Sets the current record's "updated_at" value
 * @method ArPlot              setCountry()            Sets the current record's "Country" value
 * @method ArPlot              setCemCemetery()        Sets the current record's "CemCemetery" value
 * @method ArPlot              setArArea()             Sets the current record's "ArArea" value
 * @method ArPlot              setArSection()          Sets the current record's "ArSection" value
 * @method ArPlot              setArRow()              Sets the current record's "ArRow" value
 * @method ArPlot              setArGrave()            Sets the current record's "ArGrave" collection
 * @method ArPlot              setArGraveMaintenance() Sets the current record's "ArGraveMaintenance" collection
 * @method ArPlot              setGrantee()            Sets the current record's "Grantee" collection
 * @method ArPlot              setGraveLink()          Sets the current record's "GraveLink" collection
 * @method ArPlot              setIntermentBooking()   Sets the current record's "IntermentBooking" collection
 * @method ArPlot              setWorkflow()           Sets the current record's "Workflow" collection
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArPlot extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ar_plot');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('country_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cem_cemetery_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_area_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_section_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_row_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('plot_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('is_enabled', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('plot_user', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('length', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('width', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('depth', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('plot_map_path', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id'));

        $this->hasOne('CemCemetery', array(
             'local' => 'cem_cemetery_id',
             'foreign' => 'id'));

        $this->hasOne('ArArea', array(
             'local' => 'ar_area_id',
             'foreign' => 'id'));

        $this->hasOne('ArSection', array(
             'local' => 'ar_section_id',
             'foreign' => 'id'));

        $this->hasOne('ArRow', array(
             'local' => 'ar_row_id',
             'foreign' => 'id'));

        $this->hasMany('ArGrave', array(
             'local' => 'id',
             'foreign' => 'ar_plot_id'));

        $this->hasMany('ArGraveMaintenance', array(
             'local' => 'id',
             'foreign' => 'ar_plot_id'));

        $this->hasMany('Grantee', array(
             'local' => 'id',
             'foreign' => 'ar_plot_id'));

        $this->hasMany('GraveLink', array(
             'local' => 'id',
             'foreign' => 'ar_plot_id'));

        $this->hasMany('IntermentBooking', array(
             'local' => 'id',
             'foreign' => 'ar_plot_id'));

        $this->hasMany('Workflow', array(
             'local' => 'id',
             'foreign' => 'ar_plot_id'));
    }
}