<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Language', 'doctrine');

/**
 * BaseLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $language_name
 * @property string $culture
 * @property integer $is_enabled
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer   getId()            Returns the current record's "id" value
 * @method string    getLanguageName()  Returns the current record's "language_name" value
 * @method string    getCulture()       Returns the current record's "culture" value
 * @method integer   getIsEnabled()     Returns the current record's "is_enabled" value
 * @method timestamp getCreatedAt()     Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()     Returns the current record's "updated_at" value
 * @method Language  setId()            Sets the current record's "id" value
 * @method Language  setLanguageName()  Sets the current record's "language_name" value
 * @method Language  setCulture()       Sets the current record's "culture" value
 * @method Language  setIsEnabled()     Sets the current record's "is_enabled" value
 * @method Language  setCreatedAt()     Sets the current record's "created_at" value
 * @method Language  setUpdatedAt()     Sets the current record's "updated_at" value
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('language');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('language_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('culture', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('is_enabled', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}