<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('IntermentBooking', 'doctrine');

/**
 * BaseIntermentBooking
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $country_id
 * @property integer $cem_cemetery_id
 * @property integer $ar_area_id
 * @property integer $ar_section_id
 * @property integer $ar_row_id
 * @property integer $ar_plot_id
 * @property integer $ar_grave_id
 * @property integer $ar_grave_status
 * @property integer $denomination_id
 * @property integer $fnd_fndirector_id
 * @property integer $service_type_id
 * @property integer $cem_stonemason_id
 * @property integer $catalog_id
 * @property integer $payment_id
 * @property string $deceased_title
 * @property string $deceased_surname
 * @property string $deceased_first_name
 * @property string $deceased_middle_name
 * @property string $deceased_other_surname
 * @property string $deceased_other_first_name
 * @property string $deceased_other_middle_name
 * @property enum $deceased_gender
 * @property date $date_notified
 * @property string $consultant
 * @property date $service_date
 * @property string $date1_day
 * @property time $service_booking_time_from
 * @property time $service_booking_time_to
 * @property date $service_date2
 * @property string $date2_day
 * @property time $service_booking2_time_from
 * @property time $service_booking2_time_to
 * @property date $service_date3
 * @property string $date3_day
 * @property time $service_booking3_time_from
 * @property time $service_booking3_time_to
 * @property string $monument
 * @property string $monuments_grave_position
 * @property integer $monuments_unit_type
 * @property integer $monuments_depth
 * @property integer $monuments_width
 * @property integer $monuments_length
 * @property string $grantee_first_name
 * @property string $grantee_surname
 * @property integer $grantee_id
 * @property string $grantee_relationship
 * @property string $grave_size
 * @property string $grave_length
 * @property string $grave_width
 * @property string $grave_depth
 * @property integer $grave_unit_type
 * @property integer $is_finalized
 * @property integer $is_private
 * @property date $interment_date
 * @property integer $taken_by
 * @property integer $confirmed
 * @property string $comment1
 * @property string $comment2
 * @property integer $user_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Country $Country
 * @property CemCemetery $CemCemetery
 * @property ArArea $ArArea
 * @property ArSection $ArSection
 * @property ArRow $ArRow
 * @property ArPlot $ArPlot
 * @property ArGrave $ArGrave
 * @property ServiceType $ServiceType
 * @property Catalog $Catalog
 * @property Doctrine_Collection $IntermentBookingDocs
 * @property Doctrine_Collection $IntermentBookingFive
 * @property Doctrine_Collection $IntermentBookingFour
 * @property Doctrine_Collection $IntermentBookingThree
 * @property Doctrine_Collection $IntermentBookingTwo
 * 
 * @method integer             getId()                         Returns the current record's "id" value
 * @method integer             getCountryId()                  Returns the current record's "country_id" value
 * @method integer             getCemCemeteryId()              Returns the current record's "cem_cemetery_id" value
 * @method integer             getArAreaId()                   Returns the current record's "ar_area_id" value
 * @method integer             getArSectionId()                Returns the current record's "ar_section_id" value
 * @method integer             getArRowId()                    Returns the current record's "ar_row_id" value
 * @method integer             getArPlotId()                   Returns the current record's "ar_plot_id" value
 * @method integer             getArGraveId()                  Returns the current record's "ar_grave_id" value
 * @method integer             getArGraveStatus()              Returns the current record's "ar_grave_status" value
 * @method integer             getDenominationId()             Returns the current record's "denomination_id" value
 * @method integer             getFndFndirectorId()            Returns the current record's "fnd_fndirector_id" value
 * @method integer             getServiceTypeId()              Returns the current record's "service_type_id" value
 * @method integer             getCemStonemasonId()            Returns the current record's "cem_stonemason_id" value
 * @method integer             getCatalogId()                  Returns the current record's "catalog_id" value
 * @method integer             getPaymentId()                  Returns the current record's "payment_id" value
 * @method string              getDeceasedTitle()              Returns the current record's "deceased_title" value
 * @method string              getDeceasedSurname()            Returns the current record's "deceased_surname" value
 * @method string              getDeceasedFirstName()          Returns the current record's "deceased_first_name" value
 * @method string              getDeceasedMiddleName()         Returns the current record's "deceased_middle_name" value
 * @method string              getDeceasedOtherSurname()       Returns the current record's "deceased_other_surname" value
 * @method string              getDeceasedOtherFirstName()     Returns the current record's "deceased_other_first_name" value
 * @method string              getDeceasedOtherMiddleName()    Returns the current record's "deceased_other_middle_name" value
 * @method enum                getDeceasedGender()             Returns the current record's "deceased_gender" value
 * @method date                getDateNotified()               Returns the current record's "date_notified" value
 * @method string              getConsultant()                 Returns the current record's "consultant" value
 * @method date                getServiceDate()                Returns the current record's "service_date" value
 * @method string              getDate1Day()                   Returns the current record's "date1_day" value
 * @method time                getServiceBookingTimeFrom()     Returns the current record's "service_booking_time_from" value
 * @method time                getServiceBookingTimeTo()       Returns the current record's "service_booking_time_to" value
 * @method date                getServiceDate2()               Returns the current record's "service_date2" value
 * @method string              getDate2Day()                   Returns the current record's "date2_day" value
 * @method time                getServiceBooking2TimeFrom()    Returns the current record's "service_booking2_time_from" value
 * @method time                getServiceBooking2TimeTo()      Returns the current record's "service_booking2_time_to" value
 * @method date                getServiceDate3()               Returns the current record's "service_date3" value
 * @method string              getDate3Day()                   Returns the current record's "date3_day" value
 * @method time                getServiceBooking3TimeFrom()    Returns the current record's "service_booking3_time_from" value
 * @method time                getServiceBooking3TimeTo()      Returns the current record's "service_booking3_time_to" value
 * @method string              getMonument()                   Returns the current record's "monument" value
 * @method string              getMonumentsGravePosition()     Returns the current record's "monuments_grave_position" value
 * @method integer             getMonumentsUnitType()          Returns the current record's "monuments_unit_type" value
 * @method integer             getMonumentsDepth()             Returns the current record's "monuments_depth" value
 * @method integer             getMonumentsWidth()             Returns the current record's "monuments_width" value
 * @method integer             getMonumentsLength()            Returns the current record's "monuments_length" value
 * @method string              getGranteeFirstName()           Returns the current record's "grantee_first_name" value
 * @method string              getGranteeSurname()             Returns the current record's "grantee_surname" value
 * @method integer             getGranteeId()                  Returns the current record's "grantee_id" value
 * @method string              getGranteeRelationship()        Returns the current record's "grantee_relationship" value
 * @method string              getGraveSize()                  Returns the current record's "grave_size" value
 * @method string              getGraveLength()                Returns the current record's "grave_length" value
 * @method string              getGraveWidth()                 Returns the current record's "grave_width" value
 * @method string              getGraveDepth()                 Returns the current record's "grave_depth" value
 * @method integer             getGraveUnitType()              Returns the current record's "grave_unit_type" value
 * @method integer             getIsFinalized()                Returns the current record's "is_finalized" value
 * @method integer             getIsPrivate()                  Returns the current record's "is_private" value
 * @method date                getIntermentDate()              Returns the current record's "interment_date" value
 * @method integer             getTakenBy()                    Returns the current record's "taken_by" value
 * @method integer             getConfirmed()                  Returns the current record's "confirmed" value
 * @method string              getComment1()                   Returns the current record's "comment1" value
 * @method string              getComment2()                   Returns the current record's "comment2" value
 * @method integer             getUserId()                     Returns the current record's "user_id" value
 * @method timestamp           getCreatedAt()                  Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()                  Returns the current record's "updated_at" value
 * @method Country             getCountry()                    Returns the current record's "Country" value
 * @method CemCemetery         getCemCemetery()                Returns the current record's "CemCemetery" value
 * @method ArArea              getArArea()                     Returns the current record's "ArArea" value
 * @method ArSection           getArSection()                  Returns the current record's "ArSection" value
 * @method ArRow               getArRow()                      Returns the current record's "ArRow" value
 * @method ArPlot              getArPlot()                     Returns the current record's "ArPlot" value
 * @method ArGrave             getArGrave()                    Returns the current record's "ArGrave" value
 * @method ServiceType         getServiceType()                Returns the current record's "ServiceType" value
 * @method Catalog             getCatalog()                    Returns the current record's "Catalog" value
 * @method Doctrine_Collection getIntermentBookingDocs()       Returns the current record's "IntermentBookingDocs" collection
 * @method Doctrine_Collection getIntermentBookingFive()       Returns the current record's "IntermentBookingFive" collection
 * @method Doctrine_Collection getIntermentBookingFour()       Returns the current record's "IntermentBookingFour" collection
 * @method Doctrine_Collection getIntermentBookingThree()      Returns the current record's "IntermentBookingThree" collection
 * @method Doctrine_Collection getIntermentBookingTwo()        Returns the current record's "IntermentBookingTwo" collection
 * @method IntermentBooking    setId()                         Sets the current record's "id" value
 * @method IntermentBooking    setCountryId()                  Sets the current record's "country_id" value
 * @method IntermentBooking    setCemCemeteryId()              Sets the current record's "cem_cemetery_id" value
 * @method IntermentBooking    setArAreaId()                   Sets the current record's "ar_area_id" value
 * @method IntermentBooking    setArSectionId()                Sets the current record's "ar_section_id" value
 * @method IntermentBooking    setArRowId()                    Sets the current record's "ar_row_id" value
 * @method IntermentBooking    setArPlotId()                   Sets the current record's "ar_plot_id" value
 * @method IntermentBooking    setArGraveId()                  Sets the current record's "ar_grave_id" value
 * @method IntermentBooking    setArGraveStatus()              Sets the current record's "ar_grave_status" value
 * @method IntermentBooking    setDenominationId()             Sets the current record's "denomination_id" value
 * @method IntermentBooking    setFndFndirectorId()            Sets the current record's "fnd_fndirector_id" value
 * @method IntermentBooking    setServiceTypeId()              Sets the current record's "service_type_id" value
 * @method IntermentBooking    setCemStonemasonId()            Sets the current record's "cem_stonemason_id" value
 * @method IntermentBooking    setCatalogId()                  Sets the current record's "catalog_id" value
 * @method IntermentBooking    setPaymentId()                  Sets the current record's "payment_id" value
 * @method IntermentBooking    setDeceasedTitle()              Sets the current record's "deceased_title" value
 * @method IntermentBooking    setDeceasedSurname()            Sets the current record's "deceased_surname" value
 * @method IntermentBooking    setDeceasedFirstName()          Sets the current record's "deceased_first_name" value
 * @method IntermentBooking    setDeceasedMiddleName()         Sets the current record's "deceased_middle_name" value
 * @method IntermentBooking    setDeceasedOtherSurname()       Sets the current record's "deceased_other_surname" value
 * @method IntermentBooking    setDeceasedOtherFirstName()     Sets the current record's "deceased_other_first_name" value
 * @method IntermentBooking    setDeceasedOtherMiddleName()    Sets the current record's "deceased_other_middle_name" value
 * @method IntermentBooking    setDeceasedGender()             Sets the current record's "deceased_gender" value
 * @method IntermentBooking    setDateNotified()               Sets the current record's "date_notified" value
 * @method IntermentBooking    setConsultant()                 Sets the current record's "consultant" value
 * @method IntermentBooking    setServiceDate()                Sets the current record's "service_date" value
 * @method IntermentBooking    setDate1Day()                   Sets the current record's "date1_day" value
 * @method IntermentBooking    setServiceBookingTimeFrom()     Sets the current record's "service_booking_time_from" value
 * @method IntermentBooking    setServiceBookingTimeTo()       Sets the current record's "service_booking_time_to" value
 * @method IntermentBooking    setServiceDate2()               Sets the current record's "service_date2" value
 * @method IntermentBooking    setDate2Day()                   Sets the current record's "date2_day" value
 * @method IntermentBooking    setServiceBooking2TimeFrom()    Sets the current record's "service_booking2_time_from" value
 * @method IntermentBooking    setServiceBooking2TimeTo()      Sets the current record's "service_booking2_time_to" value
 * @method IntermentBooking    setServiceDate3()               Sets the current record's "service_date3" value
 * @method IntermentBooking    setDate3Day()                   Sets the current record's "date3_day" value
 * @method IntermentBooking    setServiceBooking3TimeFrom()    Sets the current record's "service_booking3_time_from" value
 * @method IntermentBooking    setServiceBooking3TimeTo()      Sets the current record's "service_booking3_time_to" value
 * @method IntermentBooking    setMonument()                   Sets the current record's "monument" value
 * @method IntermentBooking    setMonumentsGravePosition()     Sets the current record's "monuments_grave_position" value
 * @method IntermentBooking    setMonumentsUnitType()          Sets the current record's "monuments_unit_type" value
 * @method IntermentBooking    setMonumentsDepth()             Sets the current record's "monuments_depth" value
 * @method IntermentBooking    setMonumentsWidth()             Sets the current record's "monuments_width" value
 * @method IntermentBooking    setMonumentsLength()            Sets the current record's "monuments_length" value
 * @method IntermentBooking    setGranteeFirstName()           Sets the current record's "grantee_first_name" value
 * @method IntermentBooking    setGranteeSurname()             Sets the current record's "grantee_surname" value
 * @method IntermentBooking    setGranteeId()                  Sets the current record's "grantee_id" value
 * @method IntermentBooking    setGranteeRelationship()        Sets the current record's "grantee_relationship" value
 * @method IntermentBooking    setGraveSize()                  Sets the current record's "grave_size" value
 * @method IntermentBooking    setGraveLength()                Sets the current record's "grave_length" value
 * @method IntermentBooking    setGraveWidth()                 Sets the current record's "grave_width" value
 * @method IntermentBooking    setGraveDepth()                 Sets the current record's "grave_depth" value
 * @method IntermentBooking    setGraveUnitType()              Sets the current record's "grave_unit_type" value
 * @method IntermentBooking    setIsFinalized()                Sets the current record's "is_finalized" value
 * @method IntermentBooking    setIsPrivate()                  Sets the current record's "is_private" value
 * @method IntermentBooking    setIntermentDate()              Sets the current record's "interment_date" value
 * @method IntermentBooking    setTakenBy()                    Sets the current record's "taken_by" value
 * @method IntermentBooking    setConfirmed()                  Sets the current record's "confirmed" value
 * @method IntermentBooking    setComment1()                   Sets the current record's "comment1" value
 * @method IntermentBooking    setComment2()                   Sets the current record's "comment2" value
 * @method IntermentBooking    setUserId()                     Sets the current record's "user_id" value
 * @method IntermentBooking    setCreatedAt()                  Sets the current record's "created_at" value
 * @method IntermentBooking    setUpdatedAt()                  Sets the current record's "updated_at" value
 * @method IntermentBooking    setCountry()                    Sets the current record's "Country" value
 * @method IntermentBooking    setCemCemetery()                Sets the current record's "CemCemetery" value
 * @method IntermentBooking    setArArea()                     Sets the current record's "ArArea" value
 * @method IntermentBooking    setArSection()                  Sets the current record's "ArSection" value
 * @method IntermentBooking    setArRow()                      Sets the current record's "ArRow" value
 * @method IntermentBooking    setArPlot()                     Sets the current record's "ArPlot" value
 * @method IntermentBooking    setArGrave()                    Sets the current record's "ArGrave" value
 * @method IntermentBooking    setServiceType()                Sets the current record's "ServiceType" value
 * @method IntermentBooking    setCatalog()                    Sets the current record's "Catalog" value
 * @method IntermentBooking    setIntermentBookingDocs()       Sets the current record's "IntermentBookingDocs" collection
 * @method IntermentBooking    setIntermentBookingFive()       Sets the current record's "IntermentBookingFive" collection
 * @method IntermentBooking    setIntermentBookingFour()       Sets the current record's "IntermentBookingFour" collection
 * @method IntermentBooking    setIntermentBookingThree()      Sets the current record's "IntermentBookingThree" collection
 * @method IntermentBooking    setIntermentBookingTwo()        Sets the current record's "IntermentBookingTwo" collection
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIntermentBooking extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('interment_booking');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('country_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cem_cemetery_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_area_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_section_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_row_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_plot_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_grave_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ar_grave_status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('denomination_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fnd_fndirector_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('service_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cem_stonemason_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('catalog_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('payment_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('deceased_title', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('deceased_surname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('deceased_first_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('deceased_middle_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('deceased_other_surname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('deceased_other_first_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('deceased_other_middle_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('deceased_gender', 'enum', 12, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Male',
              1 => 'Female',
              2 => 'Trans-Gender',
             ),
             'primary' => false,
             'default' => 'Male',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('date_notified', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('consultant', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('service_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('date1_day', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('service_booking_time_from', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('service_booking_time_to', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('service_date2', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('date2_day', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('service_booking2_time_from', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('service_booking2_time_to', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('service_date3', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('date3_day', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('service_booking3_time_from', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('service_booking3_time_to', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('monument', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('monuments_grave_position', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('monuments_unit_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('monuments_depth', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('monuments_width', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('monuments_length', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('grantee_first_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('grantee_surname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('grantee_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('grantee_relationship', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('grave_size', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('grave_length', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('grave_width', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('grave_depth', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('grave_unit_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_finalized', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_private', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('interment_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('taken_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('confirmed', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('comment1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('comment2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id'));

        $this->hasOne('CemCemetery', array(
             'local' => 'cem_cemetery_id',
             'foreign' => 'id'));

        $this->hasOne('ArArea', array(
             'local' => 'ar_area_id',
             'foreign' => 'id'));

        $this->hasOne('ArSection', array(
             'local' => 'ar_section_id',
             'foreign' => 'id'));

        $this->hasOne('ArRow', array(
             'local' => 'ar_row_id',
             'foreign' => 'id'));

        $this->hasOne('ArPlot', array(
             'local' => 'ar_plot_id',
             'foreign' => 'id'));

        $this->hasOne('ArGrave', array(
             'local' => 'ar_grave_id',
             'foreign' => 'id'));

        $this->hasOne('ServiceType', array(
             'local' => 'service_type_id',
             'foreign' => 'id'));

        $this->hasOne('Catalog', array(
             'local' => 'catalog_id',
             'foreign' => 'id'));

        $this->hasMany('IntermentBookingDocs', array(
             'local' => 'id',
             'foreign' => 'interment_booking_id'));

        $this->hasMany('IntermentBookingFive', array(
             'local' => 'id',
             'foreign' => 'interment_booking_id'));

        $this->hasMany('IntermentBookingFour', array(
             'local' => 'id',
             'foreign' => 'interment_booking_id'));

        $this->hasMany('IntermentBookingThree', array(
             'local' => 'id',
             'foreign' => 'interment_booking_id'));

        $this->hasMany('IntermentBookingTwo', array(
             'local' => 'id',
             'foreign' => 'interment_booking_id'));
    }
}