<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FndServiceFndirector', 'doctrine');

/**
 * BaseFndServiceFndirector
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $fnd_fndirector_id
 * @property integer $fnd_service_id
 * @property FndService $FndService
 * 
 * @method integer              getId()                Returns the current record's "id" value
 * @method integer              getFndFndirectorId()   Returns the current record's "fnd_fndirector_id" value
 * @method integer              getFndServiceId()      Returns the current record's "fnd_service_id" value
 * @method FndService           getFndService()        Returns the current record's "FndService" value
 * @method FndServiceFndirector setId()                Sets the current record's "id" value
 * @method FndServiceFndirector setFndFndirectorId()   Sets the current record's "fnd_fndirector_id" value
 * @method FndServiceFndirector setFndServiceId()      Sets the current record's "fnd_service_id" value
 * @method FndServiceFndirector setFndService()        Sets the current record's "FndService" value
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFndServiceFndirector extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fnd_service_fndirector');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fnd_fndirector_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('fnd_service_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FndService', array(
             'local' => 'fnd_service_id',
             'foreign' => 'id'));
    }
}