<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GranteeDetails', 'doctrine');

/**
 * BaseGranteeDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cem_id
 * @property string $title
 * @property string $grantee_first_name
 * @property string $grantee_middle_name
 * @property string $grantee_surname
 * @property string $grantee_address
 * @property string $grantee_email
 * @property string $state
 * @property string $town
 * @property string $postal_code
 * @property string $phone
 * @property string $contact_mobile
 * @property string $fax
 * @property string $fax_area_code
 * @property string $area_code
 * @property date $grantee_dob
 * @property string $grantee_id_number
 * @property string $grantee_unique_id
 * @property string $remarks_1
 * @property string $remarks_2
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property CemCemetery $CemCemetery
 * @property Doctrine_Collection $Grantee
 * @property Doctrine_Collection $GranteeGraveHistory
 * @property Doctrine_Collection $GranteeGraveHistory_3
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getCemId()                 Returns the current record's "cem_id" value
 * @method string              getTitle()                 Returns the current record's "title" value
 * @method string              getGranteeFirstName()      Returns the current record's "grantee_first_name" value
 * @method string              getGranteeMiddleName()     Returns the current record's "grantee_middle_name" value
 * @method string              getGranteeSurname()        Returns the current record's "grantee_surname" value
 * @method string              getGranteeAddress()        Returns the current record's "grantee_address" value
 * @method string              getGranteeEmail()          Returns the current record's "grantee_email" value
 * @method string              getState()                 Returns the current record's "state" value
 * @method string              getTown()                  Returns the current record's "town" value
 * @method string              getPostalCode()            Returns the current record's "postal_code" value
 * @method string              getPhone()                 Returns the current record's "phone" value
 * @method string              getContactMobile()         Returns the current record's "contact_mobile" value
 * @method string              getFax()                   Returns the current record's "fax" value
 * @method string              getFaxAreaCode()           Returns the current record's "fax_area_code" value
 * @method string              getAreaCode()              Returns the current record's "area_code" value
 * @method date                getGranteeDob()            Returns the current record's "grantee_dob" value
 * @method string              getGranteeIdNumber()       Returns the current record's "grantee_id_number" value
 * @method string              getGranteeUniqueId()       Returns the current record's "grantee_unique_id" value
 * @method string              getRemarks1()              Returns the current record's "remarks_1" value
 * @method string              getRemarks2()              Returns the current record's "remarks_2" value
 * @method timestamp           getCreatedAt()             Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()             Returns the current record's "updated_at" value
 * @method CemCemetery         getCemCemetery()           Returns the current record's "CemCemetery" value
 * @method Doctrine_Collection getGrantee()               Returns the current record's "Grantee" collection
 * @method Doctrine_Collection getGranteeGraveHistory()   Returns the current record's "GranteeGraveHistory" collection
 * @method Doctrine_Collection getGranteeGraveHistory3()  Returns the current record's "GranteeGraveHistory_3" collection
 * @method GranteeDetails      setId()                    Sets the current record's "id" value
 * @method GranteeDetails      setCemId()                 Sets the current record's "cem_id" value
 * @method GranteeDetails      setTitle()                 Sets the current record's "title" value
 * @method GranteeDetails      setGranteeFirstName()      Sets the current record's "grantee_first_name" value
 * @method GranteeDetails      setGranteeMiddleName()     Sets the current record's "grantee_middle_name" value
 * @method GranteeDetails      setGranteeSurname()        Sets the current record's "grantee_surname" value
 * @method GranteeDetails      setGranteeAddress()        Sets the current record's "grantee_address" value
 * @method GranteeDetails      setGranteeEmail()          Sets the current record's "grantee_email" value
 * @method GranteeDetails      setState()                 Sets the current record's "state" value
 * @method GranteeDetails      setTown()                  Sets the current record's "town" value
 * @method GranteeDetails      setPostalCode()            Sets the current record's "postal_code" value
 * @method GranteeDetails      setPhone()                 Sets the current record's "phone" value
 * @method GranteeDetails      setContactMobile()         Sets the current record's "contact_mobile" value
 * @method GranteeDetails      setFax()                   Sets the current record's "fax" value
 * @method GranteeDetails      setFaxAreaCode()           Sets the current record's "fax_area_code" value
 * @method GranteeDetails      setAreaCode()              Sets the current record's "area_code" value
 * @method GranteeDetails      setGranteeDob()            Sets the current record's "grantee_dob" value
 * @method GranteeDetails      setGranteeIdNumber()       Sets the current record's "grantee_id_number" value
 * @method GranteeDetails      setGranteeUniqueId()       Sets the current record's "grantee_unique_id" value
 * @method GranteeDetails      setRemarks1()              Sets the current record's "remarks_1" value
 * @method GranteeDetails      setRemarks2()              Sets the current record's "remarks_2" value
 * @method GranteeDetails      setCreatedAt()             Sets the current record's "created_at" value
 * @method GranteeDetails      setUpdatedAt()             Sets the current record's "updated_at" value
 * @method GranteeDetails      setCemCemetery()           Sets the current record's "CemCemetery" value
 * @method GranteeDetails      setGrantee()               Sets the current record's "Grantee" collection
 * @method GranteeDetails      setGranteeGraveHistory()   Sets the current record's "GranteeGraveHistory" collection
 * @method GranteeDetails      setGranteeGraveHistory3()  Sets the current record's "GranteeGraveHistory_3" collection
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGranteeDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grantee_details');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cem_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('grantee_first_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('grantee_middle_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('grantee_surname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('grantee_address', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('grantee_email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('state', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('town', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('postal_code', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('contact_mobile', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('fax', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('fax_area_code', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('area_code', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('grantee_dob', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('grantee_id_number', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('grantee_unique_id', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('remarks_1', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('remarks_2', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CemCemetery', array(
             'local' => 'cem_id',
             'foreign' => 'id'));

        $this->hasMany('Grantee', array(
             'local' => 'id',
             'foreign' => 'grantee_details_id'));

        $this->hasMany('GranteeGraveHistory', array(
             'local' => 'id',
             'foreign' => 'grantee_details_id'));

        $this->hasMany('GranteeGraveHistory as GranteeGraveHistory_3', array(
             'local' => 'id',
             'foreign' => 'grantee_details_surrender_id'));
    }
}