<?php

sfConfig::add(
    array(
        // local configuration   
        'SF_LIST_STATIC_VARIABLES'	=> array('SERVICE_TYPE','DATE_NOTIFIED','FUNERAL_DIRECTOR','CONSULTANT',
										 'SERVICE_DATE1','SERVICE_DATE_DAY','SERVICE_DATE1_TIME_FROM','SERVICE_DATE1_TIME_TO',
										 'SERVICE_DATE2','SERVICE_DATE2_DAY',
										 'SERVICE_DATE2_TIME_FROM','SERVICE_DATE2_TIME_TO','SERVICE_DATE3','SERVICE_DATE3_DAY',
										 'SERVICE_DATE3_TIME_FROM',
										 'SERVICE_DATE3_TIME_TO','DECEASED_SALUTATION','DECEASED_FIRSTNAME','DECEASED_MIDDLENAME','DECEASED_SURNAME','DECEASED_OTHER_SALUTATION','DECEASED_OTHER_FIRSTNAME','DECEASED_OTHER_MIDDLENAME','DECEASED_OTHER_SURNAME','DECEASED_GENDER',
										 'COFFIN_TYPE','UNIT_TYPE','COFFIN_LENGTH','COFFIN_WIDTH',
										 'COFFIN_HEIGHT','COFFIN_SURCHARGE','DEATH_CERTIFICATE','INFECTIOUS_DISEASE',
										 'OWN_CLERGY','CLERGE_NAME','CHAPEL_TYPE','CHAPEL_TIME_FROM',
										 'CHAPEL_TIME_TO','ROOM_TYPE','ROOM_TIME_FROM','ROOM_TIME_TO',
										 'BURNING_DRUM','FIREWORKS','CEREMONIAL_SAND','CANOPY',
										 'LOWRING_DEVICE','BALLONS','CHAPEL_MULTIMEDIA','COST',
										 'RECEIPT_NUMBER','SPECIAL_INSRUCTION','NOTES','COUNTRY',
										 'CEMETERY','AREA_CODE','SECTION_CODE','ROW',
										 'PLOT','GRAVE_NUMBER','GRAVE_LENGTH','GRAVE_WIDTH',
										 'GRAVE_HEIGHT','GRAVE_UNIT_TYPE','GRAVE_STATUS','GRAVE_COMMENT1',
										 'GRAVE_COMMENT2','GRANTEE_SALUTATION','GRANTEE_FIRSTNAME','GRANTEE_MIDDLENAME','GRANTEE_SURNAME','GRANTEE_ADDRESS','GRANTEE_STATE','GRANTEE_TOWN','GRANTEE_POSTAL_CODE','GRANTEE_SUBURB_STATE_POSTCODE',
										 'GRANTEE_REMARKS1','GRANTEE_REMARKS2','MONUMENT_POSITION','MONUMENT','MONUMENT_STONEMESON',
										 'MONUMENT_UNIT_TYPE','MONUMENT_DEPTH','MONUMENT_LENGTH','MONUMENT_WIDTH',
										 'INTERMENT_COMMENT1','INTERMENT_COMMENT2','CONTROL_NUMBER','INTERMENT_DATE',
										 'DATE_OF_DEATH','DATE_OF_BIRTH','PLACE_OF_DEATH','PLACE_OF_BIRTH',
										 'COUNTRY_OF_DEATH','COUNTRY_OF_BIRTH','DECEASED_AGE','DECEASED_FINAGEUOM',
										 'DECEASED_USUAL_ADDRESS','DECEASED_SUBURB_STATE_POSTCODE','DECEASED_COUNTRY','DECEASED_MARTIAL_STAUS',
										 'DECEASED_PARTNER_NAME','DECEASED_FATHER_NAME','DECEASED_MOTHER_NAME','DECEASED_CHILDREN',
										 'CULTURAL_CALENDAR_TYPE','CULTURAL_DATE_OF_DEATH','CULTURAL_DATE_OF_INTERMENT','CULTURAL_DIED_AFTER_DESK',
										 'CULTURAL_TIME_OF_DEATH','CULTURAL_DATE_OF_BIRTH','CULTURAL_STATUS','CULTURAL_REMAINS_POSITION',
										 'APPLICANT_RELATIONSHIP_WITH_DECEASED','APPLICANT_NAME','APPLICANT_EMAIL','APPLICANT_ADDRESS',
										 'APPLICANT_SUBURB_STATE_POSTCODE','APPLICANT_COUNTRY','APPLICANT_TELEPHONE_AREA_CODE','APPLICANT_TELEPHONE',
										 'APPLICANT_MOBILE','APPLICANT_FAX_AREA_CODE','APPLICANT_FAX','TODAY_DATE','STAFF_NAME',
										 ),
        'SF_LIST_STATIC_VARIABLES_CERTIFICATE' => array(
            'GRAVE_TRANSFER' => array(
                'title'     => 'Grave Transfer', 
                'variable'  => array(
                    'FROM_GRANTEE_TITLE', 'FROM_GRANTEE_NAME', 'TO_GRANTEE_TITLE', 'TO_GRANTEE_NAME', 'TRANSFER_DATE', 'AREA_NAME', 'SECTION_NAME', 
                    'ROW_NAME', 'BLOCK_PLOT_NAME', 'GRAVE_NUMBER', 'TENURE_FROM', 'TENURE_TO', 'DATE_ISSUED', 'TRANSFER_GRAVE_HISTORY'
                )
            ),
            'RIGHT_OF_BURIAL' => array(
                'title'     => 'Right of Burial', 
                'variable'  => array(
                    'GRANTEE_SALUTATION', 'GRANTEE_FIRSTNAME','GRANTEE_MIDDLENAME','GRANTEE_SURNAME','ADDRESS','TOWN','STATE','POSTALCODE','AREA_NAME', 'SECTION_NAME', 'ROW_NAME', 'BLOCK_PLOT_NAME', 'GRAVE_NUMBER', 'DATE_ISSUED'
		         )
            ),
            'BURIAL_CERTIFICATE' => array(
                'title'     => 'Burial Certificate', 
                'variable'  => array(
                    'DECEASED_SALUTATION','DECEASED_FIRSTNAME','DECEASED_MIDDLENAME','DECEASED_SURNAME','DECEASED_OTHER_SALUTATION','DECEASED_OTHER_FIRSTNAME','DECEASED_OTHER_MIDDLENAME','DECEASED_OTHER_SURNAME','DECEASED_GENDER','DATE_OF_BIRTH', 'DATE_OF_DEATH', 'DATE_OF_BURIAL', 'AREA_NAME', 'SECTION_NAME', 
                    'ROW_NAME', 'BLOCK_PLOT_NAME', 'GRAVE_NUMBER', 'DATE_ISSUED'
                )
            ),
            /*'GRAVE_LICENCE_CERT' => array(
                'title'     => 'Grave Licence Certificate', 
                'variable'  => array('GRAVE_NUMBER', 'GRAVE_RESULTS')
            ),
            'GRANTEE_BURIAL_CERT' => array(
                'title'     => 'Grave Burial Certificate', 
                'variable'  => array('GRANTEE_TITLE', 'GRANTEE_NAME', 'GRANTEE_RESULTS')
            ),*/
        ),
		'SF_COMMON_LETTER_STATIC_VARIABLES'	=> array('SELECTED_DATE','TIME','NAME','SURNAME','INTERMENT_AREA_NAME','INTERMENT_SECTION_NAME','INTERMENT_GRAVE_NUMBER'),
	)
);

class adminConfiguration extends sfApplicationConfiguration
{
  public function configure()
  {
  }
}
