# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: user, action: welcome }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_forgot_password:
  url:   /forgotPassword
  param: {module: sfGuardForgotPassword, action: index }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

sf_guard_change_password:
  url:   /changePassword
  param: { module: sfGuardAuth, action: password }


# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

# user rules
cem_mail_url:
  url:   /cemmail/index/:mail_type
  param: { module: cemmail, action: index }
  
fndprofile:
  url:   /user/profile/:id
  param: { module: user, action: profile }  
  
 
