<?php

/**
 * ArArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ArArea extends BaseArArea
{
 	public function setUp()
    { 
        parent::setUp();
        $this->actAs('Timestampable');
    }
	
	/**
	 * function saveArea
	 * @todo Function add new area table fields
	 * @static
	 * @param $amData = Area insert data
	 */
	public static function saveArea($amData)
	{
		$omArea = new ArArea();
		$omArea->setCountryId($amData['country_id']);
		$omArea->setCemCemeteryId($amData['cem_cemetery_id']);
		$omArea->setAreaCode($amData['area_code']);
		$omArea->setAreaName($amData['area_name']);
		$omArea->setAreaUser($amData['user_id']);
		$omArea->setCreatedAt(date('Y-m-d H:i:s'));
		$omArea->setUpdatedAt(date('Y-m-d H:i:s'));
		
		$omArea->save();
		
		return $omArea->getId();
	}
}
