<?php

/**
 * ArPlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ArPlot extends BaseArPlot
{
	public function setUp()
    { 
        parent::setUp();
        $this->actAs('Timestampable');
    }
	
	/**
	 * function savePlot
	 * @todo Function add new plot table fields
	 * @static
	 * @param $amData = Plot insert data
	 */
	public static function savePlot($amData)
	{
		$omPlot = new ArPlot();
		$omPlot->setCountryId($amData['country_id']);
		$omPlot->setCemCemeteryId($amData['cem_cemetery_id']);

		$omPlot->setArAreaId( ($amData['ar_area_id'] != '') ? $amData['ar_area_id'] : NULL);
		$omPlot->setArSectionId( ($amData['ar_section_id'] != '') ? $amData['ar_section_id'] : NULL);		
		$omPlot->setArRowId( ($amData['ar_row_id'] != '') ? $amData['ar_row_id'] : NULL);

		$omPlot->setPlotName($amData['plot_name']);
		$omPlot->setPlotUser($amData['user_id']);
		$omPlot->setCreatedAt(date('Y-m-d H:i:s'));
		$omPlot->setUpdatedAt(date('Y-m-d H:i:s'));
		
		$omPlot->save();
		
		return $omPlot->getId();
	}
}
