<?php

/**
 * ArRow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ArRow extends BaseArRow
{
	public function setUp()
    { 
        parent::setUp();
        $this->actAs('Timestampable');
    }
	
	/**
	 * function saveRow
	 * @todo Function add new row table fields
	 * @static
	 * @param $amData = Row insert data
	 */
	public static function saveRow($amData)
	{
		$omRow = new ArRow();
		$omRow->setCountryId($amData['country_id']);
		$omRow->setCemCemeteryId($amData['cem_cemetery_id']);
		
		$omRow->setArAreaId( ($amData['ar_area_id'] != '') ? $amData['ar_area_id'] : NULL);
		$omRow->setArSectionId( ($amData['ar_section_id'] != '') ? $amData['ar_section_id'] : NULL);
		
		$omRow->setRowName($amData['row_name']);
		$omRow->setRowUser($amData['user_id']);
		$omRow->setCreatedAt(date('Y-m-d H:i:s'));
		$omRow->setUpdatedAt(date('Y-m-d H:i:s'));
		
		$omRow->save();
		
		return $omRow->getId();
	}
}
