<?php

/**
 * ArSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ArSection extends BaseArSection
{
	public function setUp()
    { 
        parent::setUp();
        $this->actAs('Timestampable');
    }
	
	/**
	 * function saveSection
	 * @todo Function add new section table fields
	 * @static
	 * @param $amData = Section insert data
	 */
	public static function saveSection($amData)
	{
		$omSection = new ArSection();
		$omSection->setCountryId($amData['country_id']);
		$omSection->setCemCemeteryId($amData['cem_cemetery_id']);
		$omSection->setArAreaId( ($amData['ar_area_id'] != '') ? $amData['ar_area_id'] : NULL);
		$omSection->setSectionCode($amData['section_code']);
		$omSection->setSectionName($amData['section_name']);
		$omSection->setSectionUser($amData['user_id']);
		$omSection->setCreatedAt(date('Y-m-d H:i:s'));
		$omSection->setUpdatedAt(date('Y-m-d H:i:s'));
		
		$omSection->save();

		return $omSection->getId();
	}
	
}
