<?php

/**
 * AwardPayRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Arpita Rana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AwardPayRate extends BaseAwardPayRate
{
    /*
	 * Function saveAwardPayDetail
	 * @todo Function For save AwardPayDetail
	 * @param time $snIdAward      Award id.
	 * @param int  $snAwardHrs     Award Hrs..
     * @param int  $snAwardPayRate Award Par rate.
	 * @return querystring
	 */
    public function saveAwardPayDetail($snIdAward,$snAwardHrs,$snAwardPayRate)
    {
        //if($snIdAward != '' && $snAwardHrs != '' && $snAwardPayRate != '' && is_numeric($snIdAward))
		//{
            $this->setIdAward($snIdAward);
            $this->setOvertimeHrs($snAwardHrs.':00:00');
            $this->setOvertimePayRate($snAwardPayRate);
            $this->save();
            return true;
        //}
        //else
           // return false;
    }
    
    /*
	 * Function updatePageSize
	 * @todo Function For Change TimeInOut detail Of User
	 * @param time $snCurrentTime current time
	 * @param int  $snTotalHrs    Total hrs.
     * @param int  $ssStatus      Status.
	 * @return querystring
	 */
    public function updateAwardPayDetail($snIdAward,$snOverTime, $snOverTimePayRate)
    {
        if($snIdAward != '' && $snOverTime != '' && $snOverTimePayRate != '' && is_numeric($snIdAward))
		{
            $oResult = Doctrine_Query::create()
			->update('AwardPayRate')
            ->set('overtime_hrs','?',$snOverTime.':00:00')
            ->set('overtime_pay_rate','?',$snOverTimePayRate)
            ->where('id =?',$snIdAward)
            ->execute();
            return true;
        }
        else
            return false;
    }
}
