<?php

/**
 * DepartmentDelegation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Prakash Panchal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DepartmentDelegation extends BaseDepartmentDelegation
{
	public function setUp()
    { 
        parent::setUp();
        $this->actAs('Timestampable');
    }
	/**
     * Function for check name exists or not.
     *
     * @access  public
     * @param   string  $smName name.
     * @param   integer $snIdDepartment Optional - department id.
     * @return  mixed   object|boolean  object of record set, or
     *                  false if parameter is null
     */
    public function checkDepartmentNameExist($smName, $snIdDepartment = '')
    {
        if($smName == '') return false;

        $oQuery = Doctrine_Query::create()
                                ->select('dd.name')
                                ->from('DepartmentDelegation dd')
                                ->where('dd.name = ?', $smName);
                            
        if($snIdDepartment)
            $oQuery->andwhere('dd.id != ?', $snIdDepartment);

        return $oQuery->execute();
    }	
}
