<?php

/**
 * GranteeGraveHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GranteeGraveHistory extends BaseGranteeGraveHistory
{
	public function setUp()
    { 
        parent::setUp();
        $this->actAs('Timestampable');
    }
	/**
	 * function updateGraveHistoryField
	 * @todo Function update grave history tables fields
	 * @static
	 * @param $ssFieldName = field name
	 * @param $ssFieldValue = field value
	 * @param $ssCompareField = compare field
	 * @param $smCompareValue = compare value
	 */
	public static function updateGraveHistoryField($ssFieldName, $ssFieldValue, $ssCompareField, $smCompareValue)
	{
		$oHistory = Doctrine_Query::create()
					->update('GranteeGraveHistory')
					->set($ssFieldName,'?',$ssFieldValue)
					->where($ssCompareField.' = ?', $smCompareValue)
					->execute();
		return true;
	}
}
