<?php

/**
 * Grantee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Grantee extends BaseGrantee
{
	public function setUp()
    { 
        parent::setUp();
        $this->actAs('Timestampable');
    }
	/**
	 * function saveGranteeRecords
	 * @todo Function add new graves tables fields
	 * @static
	 * @param $amData = Grave insert data
	 */
	public static function saveGranteeRecords($amData)
	{
		$snAreaId = ($amData['area_id'] != '') ? $amData['area_id'] : NULL;
		$snSectionId = ($amData['section_id'] != '') ? $amData['section_id'] : NULL;
		$snRowId = ($amData['row_id'] != '') ? $amData['row_id'] : NULL;
		$snPlotId = ($amData['plot_id'] != '') ? $amData['plot_id'] : NULL;

		$oGrantee = new Grantee();
		$oGrantee->setGranteeDetailsId($amData['grantee_id']);
		
		$oGrantee->setCountryId($amData['country_id']);
		$oGrantee->setCemCemeteryId($amData['cemetery_id']);
		
		$oGrantee->setArAreaId($snAreaId);
		$oGrantee->setArSectionId($snSectionId);
		$oGrantee->setArRowId($snRowId);
		$oGrantee->setArPlotId($snPlotId);
		
		$oGrantee->setArGraveId($amData['grave_id']);
		$oGrantee->setGranteeIdentityId(1);
		
		if(isset($amData['date_of_purchase']) && $amData['date_of_purchase'] != '')
			$oGrantee->setDateOfPurchase($amData['date_of_purchase']);

		if(isset($amData['tenure_expiry_date']) && $amData['tenure_expiry_date'] != '')
			$oGrantee->setTenureExpiryDate($amData['tenure_expiry_date']);

		if(isset($amData['grantee_identity_id']) && $amData['grantee_identity_id'] != '')
			$oGrantee->setGranteeIdentityId($amData['grantee_identity_id']);

		if(isset($amData['grantee_identity_number']))
			$oGrantee->setGranteeIdentityNumber($amData['grantee_identity_number']);
		
		$oGrantee->setUserId($amData['user_id']);
		$oGrantee->save();

		// Update Grave status into grave table.
		$oGrave = Doctrine::getTable('ArGrave')->find($oGrantee->getArGraveId());
		if($oGrave)
		{
			if($oGrave->getArGraveStatusId() == sfConfig::get('app_grave_status_vacant'))
				ArGrave::updateGraveTableField('ar_grave_status_id', sfConfig::get('app_grave_status_pre_Purchased'), $oGrantee->getArGraveId());
		}

		unset($oGrantee);
	}
}
