<?php

/**
 * GranteeDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Prakash Panchal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GranteeDetails extends BaseGranteeDetails
{
	public function setUp()
    { 
        parent::setUp();
        $this->actAs('Timestampable');
    }
	/**
	 * function updateGranteeUniqueID
	 * @todo Function update grantee tables fields
	 * @static
	 * @param $snIdGrantee = Grantee ID
	 */
	public static function updateGranteeUniqueID($snIdGrantee)
	{
		$ssUniqueID = $snIdGrantee.strtoupper(uniqid());
		$oQuery = Doctrine_Query::create()
				->update('GranteeDetails')
				->set('grantee_unique_id','?',$ssUniqueID)
				->where('id = ?', $snIdGrantee);
				
		$oQuery->execute();
	}
	/**
	 * function updateGranteeRemarks
	 * @todo Function update grantee remarks from booking side
	 * @static
	 */
	public static function updateGranteeRemarks($ssRemarks1, $ssRemarks2, $snGranteeId)
	{
		$oQuery = Doctrine_Query::create()
				->update('GranteeDetails')
				->set('remarks_1','?',$ssRemarks1)
				->set('remarks_2','?',$ssRemarks2)
				->where('id = ?', $snGranteeId);
				
		$oQuery->execute();
	}
	
	/**
	 * function saveGranteeRecords
	 * @todo Function add new grantee records
	 * @static
	 * @param $amData = Grantee insert data
	 */
	public static function saveGranteeRecords($amData)
	{
		$oGranteeDetail = new GranteeDetails();

		$oGranteeDetail->setCemId($amData['cem_cemetery_id']);
		$oGranteeDetail->setGranteeFirstName($amData['grantee_first_name']);
		$oGranteeDetail->setGranteeSurname($amData['grantee_surname']);
		$oGranteeDetail->setGranteeAddress($amData['grantee_address']);
		$oGranteeDetail->setTown($amData['town']);
		$oGranteeDetail->setRemarks_1($amData['remarks_1']);
		$oGranteeDetail->setRemarks_2($amData['remarks_2']);
		$oGranteeDetail->setCreatedAt(date('Y-m-d H:i:s'));
		$oGranteeDetail->setUpdatedAt(date('Y-m-d H:i:s'));

		$oGranteeDetail->save();
		$snGranteeId = $oGranteeDetail->getId();		
		self::updateGranteeUniqueID($snGranteeId);
		
		unset($oGranteeDetail);
		
		// SAVE GRAVE DETAILS FOR GRANTEE.
		$oGrantee = new Grantee();
		$oGrantee->setGranteeDetailsId($snGranteeId);
		$oGrantee->setCountryId($amData['country_id']);
		$oGrantee->setCemCemeteryId($amData['cem_cemetery_id']);
		$oGrantee->setArAreaId( ($amData['ar_area_id'] != '') ? $amData['ar_area_id'] : NULL);
		$oGrantee->setArSectionId( ($amData['ar_section_id'] != '') ? $amData['ar_section_id'] : NULL);		
		$oGrantee->setArRowId( ($amData['ar_row_id'] != '') ? $amData['ar_row_id'] : NULL);
		$oGrantee->setArPlotId( ($amData['ar_plot_id'] != '') ? $amData['ar_plot_id'] : NULL);	
		$oGrantee->setArGraveId($amData['ar_grave_id']);
		$oGrantee->setGranteeIdentityId(1);
		$oGrantee->setDateOfPurchase( $amData['date_of_purchase'] );
		$oGrantee->setUserId(sfContext::getInstance()->getUser()->getAttribute('userid'));
		$oGrantee->setCreatedAt(date('Y-m-d H:i:s'));
		$oGrantee->setUpdatedAt(date('Y-m-d H:i:s'));
		
		$oGrantee->save();
		
		// UPDATE GRAVE STATUS WHILE ANY GRANTEE PURCHASE IT.
		ArGrave::updateGraveTableField('ar_grave_status_id',sfConfig::get('app_grave_status_pre_Purchased'),$oGrantee->getArGraveId());
		unset($oGrantee);
	}

}
