<?php

/**
 * MailContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Prakash Panchal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MailContent extends BaseMailContent
{
	/**
	 * function insertMailContentAsPerCemetery
	 * @todo Function add new grantee records
	 * @static
	 * @param $amData = Mail Content Records array
	 */
	public static function insertMailContentAsPerCemetery($snCountry, $snCemetery, $amData)
	{
		foreach($amData as $asValues)
		{
			$oMailContent = new MailContent();
	
			$oMailContent->setCountryId($snCountry);
			$oMailContent->setCemCemeteryId($snCemetery);
			$oMailContent->setCreatedAt(date('Y-m-d H:i:s'));
			$oMailContent->setUpdatedAt(date('Y-m-d H:i:s'));
			$oMailContent->setSubject($asValues['subject']);
			$oMailContent->setContent($asValues['content']);
			$oMailContent->setContentType($asValues['content_type']);
            $oMailContent->setType($asValues['type']);

			$oMailContent->save();

			unset($oMailContent);
		}
	}
}
