<?php

/**
 * UserCemetery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cemetery
 * @subpackage model
 * @author     Prakash Panchal
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserCemetery extends BaseUserCemetery
{
	public function setUp()
    { 
        parent::setUp();
        $this->actAs('Timestampable');
    }
	/**
	 * @todo Execute deleteUsersAsPerCemetery function for delete users as per 
	 * related with deleted cemetery.
	 *
	 */
	public static function deleteUsersAsPerCemetery($anUsers)
	{
		$amGuardUser= Doctrine_Query::create()
					->delete()
					->from('SfGuardUser sfg')
					->whereIn('sfg.id',$anUsers)
					->execute();
	}
	
	public static function saveUserCemeteryInfo($amData)
	{
		$oUserCemetery = new UserCemetery();
		$oUserCemetery->setUserId($amData['user_id']);
		$oUserCemetery->setGroupId(sfConfig::get('app_cemrole_manager'));
		$oUserCemetery->setCemCemeteryId($amData['cem_id']);
		$oUserCemetery->setTitle($amData['title']);
		$oUserCemetery->setOrganisation($amData['organisation']);
		$oUserCemetery->setCode($amData['code']);
		$oUserCemetery->setAddress($amData['address']);
		$oUserCemetery->setState($amData['state']);
		$oUserCemetery->setPhone($amData['phone']);
//		$oUserCemetery->setSuburb($amData['suburb']);
		$oUserCemetery->setMiddleName($amData['middle_name']);
		$oUserCemetery->setPostalCode($amData['postal_code']);
		$oUserCemetery->setFax($amData['fax']);
		$oUserCemetery->setAreaCode($amData['area_code']);
		$oUserCemetery->setFaxAreaCode($amData['fax_area_code']);
		
		$oUserCemetery->save();
	}
}
