<?php

/**
 * sfGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    arp
 * @subpackage model
 * @author     Bipin Patel
 *
 */
class sfGuardGroup extends PluginsfGuardGroup
{
    /**
     * Function for check name exists or not.
     *
     * @access  public
     * @param   string  $smName name.
     * @param   integer $snIdGroup Optional - group id.
     * @return  mixed   object|boolean  object of record set, or
     *                  false if parameter is null
     */
    public function checkGroupNameExist($smName, $snIdGroup = '')
    {
        if($smName == '') return false;

        $oQuery = Doctrine_Query::create()
                                ->select('sf.name')
                                ->from('sfGuardGroup sf')
                                ->where('sf.name = ?', $smName);
                            
        if($snIdGroup)
            $oQuery->andwhere('sf.id != ?', $snIdGroup);

        return $oQuery->execute();
    }
}
