<?php

/**
 * sfGuardPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    arp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardPermission extends PluginsfGuardPermission
{
    /**
     * Function for check name exists or not.
     *
     * @access  public
     * @param   string  $smName name.
     * @param   integer $snIdPermission Optional - permission id.
     * @return  mixed   object|boolean  object of record set, or
     *                  false if parameter is null
     */
    public function checkPermissionNameExist($smName, $snIdPermission = '')
    {
        if($smName == '') return false;

        $oQuery = Doctrine_Query::create()
                                ->select('sf.name')
                                ->from('sfGuardPermission sf')
                                ->where('sf.name = ?', $smName);
                            
        if($snIdPermission)
            $oQuery->andwhere('sf.id != ?', $snIdPermission);

        return $oQuery->execute();
    }
}
