# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Cemetery
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  #stylesheets:    [main.css, admin/style.css, datepicker/css/ui-lightness/jquery-ui-1.8.16.custom.css]

  javascripts:    [admin/common.js, datepicker/js/jquery-ui-1.8.16.custom.min.js]

  has_layout:     false
  layout:         
