<?php

/**
 * PlugincalSchedularTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugincalSchedularTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugincalSchedularTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugincalSchedular');
    }
}