<?php

/**
 * PlugincalSpecialReservationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugincalSpecialReservationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugincalSpecialReservationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugincalSpecialReservation');
    }
}