<?php

/**
 * PlugincalCalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugincalCalendarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugincalCalendarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugincalCalendar');
    }
}