<?php

/**
 * PlugincalCalendar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: PlugincalCalendar.class.php,v 1.1.1.1 2012/03/24 12:14:41 nitin Exp $
 */
abstract class PlugincalCalendar extends BasecalCalendar
{

}